### ISSUE TITLE
[Xfce] Radio buttons and checkboxes are missing?

### ISSUE THREAD

**Issue by Summer-1999** [EliverLara/Nordic#168]
![screenshot](https://user-images.githubusercontent.com/92577776/137477556-87581b50-4277-4c04-b0c4-68c9f5824fba.png)
Sceenshots of Nordic-darker vs Adwaita-dark, Xfce 4.14

**Comment by frithrah** [comment]
The problem here is how Xfce copies over the theme when you use the Add button on the Appearance panel. It copies `gtk-2.0`, `gtk-3.0` and `xfwm4` but not the root `assets` directory.

Some solutions are:

* This theme makes `assets` a child of `gtk-3.0` instead of referencing assets in the parent.
* The Xfce Appearance panel copies over the root `assets` directory when a downloaded theme is added.
* You copy the `assets` directory over manually. Copy the `assets` directory from the downloaded Nordic archive to `~/.themes/Nordic/`. Then flip the Appearance Style over and back again to reload. Works here.

**Comment by Jay-flow** [comment]
> The problem here is how Xfce copies over the theme when you use the Add button on the Appearance panel. It copies `gtk-2.0`, `gtk-3.0` and `xfwm4` but not the root `assets` directory.
> 
> Some solutions are:
> 
> * This theme makes `assets` a child of `gtk-3.0` instead of referencing assets in the parent.
> * The Xfce Appearance panel copies over the root `assets` directory when a downloaded theme is added.
> * You copy the `assets` directory over manually. Copy the `assets` directory from the downloaded Nordic archive to `~/.themes/Nordic/`. Then flip the Appearance Style over and back again to reload. Works here.

I used a different theme, but that helped me. Thank you :)
