### ISSUE TITLE
Gnome apps wont theme (calendar, settings, music etc). 

### ISSUE THREAD

**Issue by A-Committed-Dev** [EliverLara/Nordic#230]
Hi i don't know what i am doing wrong. default gnome apps will not theme (tbh i am quite a noob at this stuff). check the example pictures below
![Skærmbillede fra 2022-08-31 22-26-26](https://user-images.githubusercontent.com/103140181/187775707-a06cc6e5-15fc-45a4-a9aa-341c35262af7.png)

i am on the newest version of gnome.

**Comment by A-Committed-Dev** [comment]
every other app will, i am not sure why that is.

**Comment by EliverLara** [comment]
Hi, what's you gnome version?

**Comment by A-Committed-Dev** [comment]
42.4

**Comment by EliverLara** [comment]
Thanks, for the system apps in newer gnome versions (which use libadwaita) [this](https://github.com/odziom91/libadwaita-theme-changer) works as a temporary solution.

**Comment by subB1ss** [comment]
I have the same issues, and I've tried the temporary solution.
Still doesn't work fine for me.

I'm not sure where the problem is.
Since the scripts just create some s-link files to the assets folder and .css files, and it works fine,I guess there is something wrong with the theme file.

Here are the example pics.

before use the scripts
![image](https://user-images.githubusercontent.com/60306868/190849244-4efe0d8b-979a-45d3-8bc2-d36278115556.png)

after
![image](https://user-images.githubusercontent.com/60306868/190849282-4157b3c0-4ffa-4772-9fd4-a15c2dfd10ed.png)


GNOME Version: 42.4
Distributions: Ubuntu 22.04.1 LTS

**Comment by evilhamsterman** [comment]
@subB1ss the links created by that script don't cover everything you need. Either copy or link the full gtk-4.0 folder from the Nordic theme to $HOME/.config/gtk-4.0
