### ISSUE TITLE
Sizes / Heights seem to be off in Nautilus

### ISSUE THREAD

**Issue by RononDex** [EliverLara/Nordic#301]
See Screenshot here:
![image](https://github.com/EliverLara/Nordic/assets/2249071/55c6ae4f-35a6-4f62-8f4b-72b5ae6240ff)

The sizes of the line heights seem to be off

This is with the latest Nordic-v40 theme downloaded from gnome-looks on Arch Linux

**Comment by EliverLara** [comment]
Hi I'm sorry for the very late response, but, Could you please provide more details about you OS please? since I've been trying to reproduce this issue but it's not shown in my attempts, and it just occurs mainly in Arch based distributions.

**Comment by RononDex** [comment]
I am on Arch Linux, moved on to the Colloid themes now though.

**Comment by Hash6232** [comment]
I have a similar problem on my end. I downloaded the theme a bunch of days ago so I'm probably using an updated version.

- Linux Mint 22 with Cinnamon
- 'prefer dark mode' in themes settings
- GTK_THEME set to `Nordic-darker-v40'
- Nautilus 46.2 installed from the 'noble' ubuntu branch

I also tried using [this script](https://github.com/odziom91/libadwaita-theme-changer/blob/main/libadwaita-tc.py) to symlink the gtk-4 css files into .config/gtk-4 directory hoping to force nautilus to use the correct theme but I'm not sure if it's even doing its job.

![image](https://github.com/user-attachments/assets/3ee18dd5-1244-42cb-ae0f-cc7ac9367954)

**Comment by EliverLara** [comment]
Hi @Hash6232 , Did you download the files from gnome-look or from github?

**Comment by Hash6232** [comment]
From github. And I just noticed the files on pling are from 2024-08-20. Should I be downloading from there?

**Comment by EliverLara** [comment]
@Hash6232 Yes, please, it would be so helpful if you could download the file from pling and check how it looks

**Comment by Hash6232** [comment]
It does display everything properly  when using the files from pling. Maybe a warning in the readme, about area or download page in order to redirect people to pling can avoid these false positives in the future. Thank you anyway for replying so fast. I love your work.

![image](https://github.com/user-attachments/assets/4ed02cf1-6a4a-4024-9de5-bcc564cea3de)

**Comment by EliverLara** [comment]
@Hash6232 Does nautilus also looks correctly?

**Comment by Hash6232** [comment]
This is what nautilus looks like. I had to use [this script](https://github.com/odziom91/libadwaita-theme-changer/tree/main) to symlink the necessary css files in `~/.config/gtk-4.0` because by default the theme won't apply to nautilus. I think the only evident issues here are the different tabs and the columns bar (Name, Size, Modified) but I'll leave the details to you.

![image](https://github.com/user-attachments/assets/8758ab35-d54c-4cdd-b21f-5d63e7b70697)

![image](https://github.com/user-attachments/assets/dc3d2962-48ae-4450-9342-b019d5db5c1c)

**Comment by EliverLara** [comment]
@Hash6232 Nice, thank you so much for your help! :)
