### ISSUE TITLE
can you  update kde.store repo

### ISSUE THREAD

**Issue by Cherkah** [EliverLara/Nordic#321]
hi and thank you for your enormous work on this them.

i've posted an issue about [andromedalauncher](https://github.com/EliverLara/AndromedaLauncher/issues/18). 

1) can you update the Nordic repositories on the kde.stor.org platform?

2) considering the disclaimer you've posted on kde.org, would you still recommend installing these themes [Nordic darker KDE](https://store.kde.org/p/1629062) & [Nordic darker KDE](https://store.kde.org/p/1629062) kde.orp or via pacman/aur?

A quick response from you will allow me to take appropriate action regarding these deposits on kde.store.org

regards

**Operating System**: EndeavourOS 
KDE Plasma Version: 6.1.5
KDE Frameworks Version: 6.6.0
Qt Version: 6.7.2
Graphics Platform: Wayland

**Comment by EliverLara** [comment]
Hi, Do you mean updating the colorschemes on store.kde.org? if so there's no need to to that since color schemes in kde haven't suffered changes through the different plasma versions thats why they don't require frequent updates, it means that those color schemes are working properly in plasma v5 and v6

**Comment by Cherkah** [comment]
> Do you mean updating 

update for kvantum, kde, gtk (2,3,4) + asset and so on...

**Comment by EliverLara** [comment]
Everything is up to date and working well so far
