### ISSUE TITLE
Nautilus window focus change bugs out sidebar icons

### ISSUE THREAD

**Issue by dboekhout** [EliverLara/Nordic#52]
OS: Ubuntu 19.10
DE: Gnome 3.34.1
Nautilus: 1:3.34.1

Losing focus on the Nautilus window will cause the sidebar to bug out. Specifically the background on the icons in the sidebar.

**Focus on Nautilus window**
![image](https://user-images.githubusercontent.com/26926485/73609581-71527e80-45cf-11ea-80dc-f5832e2036e4.png)

**Unfocused Nautilus window**
![image](https://user-images.githubusercontent.com/26926485/73609630-f2117a80-45cf-11ea-8bb4-63edb1922228.png)

**Comment by EliverLara** [comment]
Hi, I'm sorry for the late response, this issue is supposed to be fixed as you can see in #8, I'm not able to reproduce this issue, maybe another attemp shoud be to completely remove the `transition` on backdrop state, so, to try this aproach, it would be very helpful if you could replace the `gtk.css `and `gtk-dark.css` files with [these others](https://github.com/EliverLara/Nordic/files/4268437/Nordic.zip). Could you do that please?

**Comment by dynobo** [comment]
Not OP, but I had the same issue, first tried the [latest release (1.8.1, Nordic.tar.gz)](https://github.com/EliverLara/Nordic/releases/tag/V1.8.1), the issue was still there, then I replaced the 2 css files as you proposed, and now it's fixed! :-)

**Comment by dboekhout** [comment]
@EliverLara just like for @dynobo your CSS files fixed the issue.
