### ISSUE TITLE
Ubuntu software app becomes completely transparent

### ISSUE THREAD

**Issue by LordRonz** [EliverLara/Nordic#70]
this bug occurs in 20.04 focal fossa
![Screenshot from 2020-05-09 14-45-42](https://user-images.githubusercontent.com/53823544/81467583-2301dc80-91c9-11ea-8382-6189a32f57f5.png)

**Comment by Razatastic** [comment]
Running into this same issue myself. Seems like a common occurrence with a number of themes.

**Comment by Belmaj** [comment]
this isnt still not fix yet lets hope Mr el will fix this soon

**Comment by toshioxgnu** [comment]
I just will post the same thing jajja

**Comment by Muqtxdir** [comment]
Ubuntu-Software is packaged as Snap-app in Ubuntu 20.04 LTS
Snap-apps only support themes which are in `gtk-common-themes` snap.
Most popular GTK-Themes and icons are ported for Snap-apps.

I guess **Nordic-theme** is not yet ported for Snaps.Hence, the problem of Transparent background in Ubuntu-Software

The only solution for this issue seems to involve reverting of theme to default `Yaru-theme`(only for Ubuntu-software) using `gtk+inspector-tool`

## Solution:
- To enable **Inspector** -> `gsettings set org.gtk.Settings.Debug enable-inspector-keybinding true` (In terminal)
- Using **GNOME-Tweaks** change the Application theme to **Yaru**
- Open Ubuntu-Software app
- Press **Ctrl+Shift+I** and Navigate to **_Visual_** Tab
- Change GTK+Theme to **Yaru**theme and close it
- Using **GNOME-Tweaks** change the Application theme back to **Nordic**
- Open Ubuntu-Software app and Now it is displayed in default Ubuntu-theme instead of being transparent 

*Note: This themeing-workaround applies to all Snap apps for any theme.*

Hope this workaround improves your situation

**Comment by Muqtxdir** [comment]
Instead of using **Ubuntu-Software**(Snap-store) one can use GNOME's **Software** app(much better) as it uses the GTK-theme and icon set applied by the user and does not require the above workaround

For installing GNOME Software on Ubuntu:
`sudo apt install gnome-software`
