### ISSUE TITLE
How to compile?

### ISSUE THREAD

**Issue by dbasinge** [EliverLara/Nordic#73]
I would like to convert this to Nordic to a flatpak, so this theme will look good on Flatpak app. How can I compile from source?

**Comment by vancanhuit** [comment]
I also curious about how to compile the source code to Nordic variants, e.g. Nordic darker.

**Comment by EliverLara** [comment]
Hi, I personally use `gulp` to generate the css files, but you can just use [sass](https://sass-lang.com/install)

If you want to use `gulp`, just move to the theme directory and run the following commands:

`npm install`

For edit and compile `gtk theme` (gtk-3.0 folder):

`gulp`

For edit and compile `gnome-shell theme` (gnome-shell folder):

`gulp shell`

For edit and compile `cinnamon theme` (cinnamon folder):

`gulp cinnamon`

**Comment by Gambloide** [comment]
For anyone coming across this while still open: The above gulp examples don't work out of the box currently.

Node-sass upgraded to 5.0.0 in Oct 2020 and removed all 4.x releases from GitHub.
This results in gulp-sass not being installable anymore, since it tries to download a 4.x release from GitHub. This is a known issue in gulp-sass: https://github.com/dlmanning/gulp-sass/pull/781
