### ISSUE TITLE
Folder Icons Symlinks Broken

### ISSUE THREAD

**Issue by lfom** [EliverLara/Nordic#77]
Hello! Thanks for theme and icons! I just installed Nordic-Folders.tar.xz and notice that some symlinks are broken, maybe you want to check them out.

Regards

**Comment by miquecg** [comment]
I think some of them still work because Nordic pulls from other themes so it doesn't have to provide all the icon set.

```
[Icon Theme]
Name=Nordic
Comment=Folders for Nordic gtk theme.
Inherits=Papirus-Dark,breeze-dark,Zafiro,ubuntu-mono-dark,Mint-X,elementary,gnome,hicolor
```

For instance `folder-downloads.svg` points to `folder-bluegrey-download.svg`, which is part of Papyrus icons. But other symlinks like `folder-unlocked.svg -> ../../actions/16/object-unlocked.svg` look like an error.

To install them I just put the folder as-is inside `~/.local/share/icons/`.
